name: Build Avatar Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/avatar-service main.go
          echo "✅ Build complete: dist/avatar-service"

      - name: Package binary
        run: |
          cd dist
          tar -czf avatar-service-linux-amd64.tar.gz avatar-service
          echo "📦 Packaged: dist/avatar-service-linux-amd64.tar.gz"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: avatar-service-linux-amd64
          path: dist/avatar-service-linux-amd64.tar.gz
